[build]
  base = "/"
  command = "./build-for-netlify.sh"
  publish = ".netlify_build/dist"
  ignore = "git diff --quiet HEAD^ HEAD -- frontend/ shared/ netlify.toml"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200